name: Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_INSTANCE_IP << 'EOF'
          cd latihan-uts-cloud-computing
          sudo git pull origin master
          sudo npm install --force
          sudo npm run build
          pm2 delete nextjs
          pm2 start npm --name "nextjs" -- start
          pm2 save
          sudo systemctl restart nginx
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        EC2_USER: ${{ secrets.EC2_USER }}
